### ISSUE TITLE
Documentation is lacking

### ISSUE THREAD

**Issue by Toerktumlare** [sitevision/webapp-boilerplate#7]
There are no examples of using restapps and working with react or angular2.

The documentation is poor, and lacking. Are you meant to write your entire application in this "sitevision" way and then deploy it to sitevision?

What if i want to develop an app in react and run my app locally.

Sitevision doesn't even have a docker. I need to "install" sitevision locally (which i will not do).

Please write better documentation where you actually use the tools that people today use.

**Comment by nguyenlinh** [comment]
react and angular2 is just javascript. how would you integrate javascript into sitevision? do it the same way as with framework x.

**Comment by robinlagren** [comment]
Since Web/RESTApps are SiteVision specific methods to develop custom functionality you need a SiteVision environment to be able to execute them.

It is possible to use frameworks such as react/angular in combination with for example a RESTApp, where the RESTApp will work as your app's backend and you can use a http requester of your choice to fetch data.

Please feel free to contact me (robin.lagren@sitevision.se) with further questions.

**Comment by Toerktumlare** [comment]
> react and angular2 is just javascript. how would you integrate javascript into sitevision? do it the same way as with framework x.

Since this is not a real answer i will ignore this.

> Since Web/RESTApps are SiteVision specific methods to develop custom functionality you need a SiteVision environment to be able to execute them.
> 
> It is possible to use frameworks such as react/angular in combination with for example a RESTApp, where the RESTApp will work as your app's backend and you can use a http requester of your choice to fetch data.
> 
> Please feel free to contact me ([robin.lagren@sitevision.se](mailto:robin.lagren@sitevision.se)) with further questions.

That Sitevision is using "Sitevision specific" implementation i have already understood, what my point is that Sitevision comes as a installable binary. Sitevision is a java application and should be providable as a docker since docker has now existed for several years it seems quite old fashion to "install" Sitevision.

RESTapp is a very confusing name. What i have understood is that a "Sitevision RESTapp" actually is a way to extend the current REST api in Sitevision. To basically turn Sitevision into some sort of a proxy.

If i host my own frontend (react app) and i host my own backend (say java spring backend) then why do i need Sitevision to proxy my requests? to aggregate? i can do that in any other proxy out there.

What i want to make clear is that the documentation is lacking in when it comes to real life workflows. How do you manage the cms side (the actual content management where you can update content in the gui) but at the same time display react apps side by side. Using the cms dynamic features as adding/removing content, menus and at the same time including/excluding react apps.

Thats where the documentation and real world examples are lacking.

**Comment by nguyenlinh** [comment]
restapp is not a proxy, it's a way to get data from sitevision without having to create a "page" as you would normally do in sitevision. it has more use cases but what i described is very common.
since there are so many frameworks out there you can't really expect sitevision to document how to integrate with every single one of them because it's basically the same procedure. first you have to convert whatever it you're using to javascript (jsx, typescript). how you convert to javascript has nothing to do with sitevision. after that you can include the javascript file/files in sitevision. it's decribed in this link https://help.sitevision.se/SiteVision_4_0/javaScriptAssetHelp.html

**Comment by Toerktumlare** [comment]
just the need to write here and to inform you that your documentation is lacking and then getting this response is enough for me.

I will not recommend my customers this solution. Have a nice day.

**Comment by nguyenlinh** [comment]
just to clarify i'm not representing sitevision, so don't base your decisions on my comments.
